language: cpp

compiler:
  - gcc
  - clang

cache: apt


before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libboost-program-options-dev  libsdl-image1.2-dev libboost-system-dev qt4-dev-tools

script:
  - cmake . $BTYPE
  - make
